# Generated by Django 5.2.6 on 2025-09-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prerequisite",
            name="course",
        ),
        migrations.RemoveField(
            model_name="section",
            name="course",
        ),
        migrations.RemoveField(
            model_name="prerequisite",
            name="prerequisite",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="department",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="section",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="student",
        ),
        migrations.AlterUniqueTogether(
            name="exam",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="exam",
            name="section",
        ),
        migrations.RemoveField(
            model_name="examresult",
            name="exam",
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="examresult",
            name="student",
        ),
        migrations.RemoveField(
            model_name="section",
            name="instructor",
        ),
        migrations.AlterUniqueTogether(
            name="prerequisite",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="section",
            name="term",
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Prerequisite",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="Exam",
        ),
        migrations.DeleteModel(
            name="ExamResult",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Instructor",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="Term",
        ),
    ]
